# a=int(input("enter a value1:"))
# b=int(input("enter a value2:"))
# try:
#     c=a/b
#     print("result is:", c)
# except Exception as e:
#     print("except is handled")
#     print("program is end")

# a=int(input("enter a value1:"))
# b=int(input("enter a value2:"))
# try:
#     c=a/b
#     print("result is:", c)
# except Exception as e:
#     print(e) #type of exception
#     print("except is handled")
#     print("program is end")

# def fun1():
#     print("entering fun1")
#     try:
#         fun2()
#     except Exception as e:
#         print("error in fun1")
#     print("leaving the fun1")
# def fun2():
#     print("entering fun2")
#     a=int(input("enter value 1:"))
#     b=int(input("enter value 2:"))
#     c=a/b
#     print("res is:",c)
#     print("leacing fun2")
# print("pgm is started")
# fun1()
# print("pgm is end")

# a=int(input("enter a value1:"))
# b=int(input("enter a value2:"))
# try:
#     c=a/b
#     print("result is:", c)
# except Exception as e:
#     print(e)
#     print("Error in pgm")
# else:
#     print("Error is not occured")

# #handling specific exception
# a=int(input("enter a value1:"))
# b=int(input("enter a value2:"))
# try:
#     c=a/b
#     print("result is:", c)
# except ZeroDivisionError as e:
#     print(e)
# except ValueError as e:
#     print(e)
# except Exception as e:
#     print(e)

# a=int(input("enter a value1:"))
# b=int(input("enter a value2:"))
# try:
#     c=a/b
#     print("result is:", c)
# except Exception as e:
#     print(e)
#     print("something went wrong")
# else:
#     print("nothinng went wrong")
# finally:
#     print("everything will get execute")







